Added reference to Uppy Dashboard Modal for Vue.js
transloadit/uppy.io pull request #162
Opened 2023-09-06 19:04 UTC by prattcmp

Documentation improvement re: https://github.com/transloadit/uppy.io/issues/160#issuecomment-1707911090

2023-09-07 11:25 UTC, arturi approved these changes

2023-09-07 11:25 UTC, arturi commented
Thank you!

2023-09-07 12:13 UTC, Murderlon requested changes
Can we also update the Angular, React, and Svelte docs to do the same while we're here?

2023-10-04 14:32 UTC, Murderlon commented
@prattcmp can you still get this PR over the finish line?

2024-04-16 13:03 UTC, merged